/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4e8a6c78-e3c7-47e2-917d-e98a7a629470",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_iQHJZrW0x",
    "aws_user_pools_web_client_id": "1ohf2vk5dthm43q37cvdgernu",
    "oauth": {}
};


export default awsmobile;
